spring:
  application:
    name: ai-study-leader
  threads:
    virtual:
      enabled: true
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
