#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/tests/testlib.sh
source "${SCRIPT_DIR}/testlib.sh"

for script in create-pr.sh verify-pr-ready.sh finish-pr.sh jira-board.sh post-role-review-pass.sh; do
  path="${TEST_ROOT}/scripts/task/${script}"
  assert_file_exists "${path}"
  bash -n "${path}"
done

assert_file_exists "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_file_exists "${TEST_ROOT}/.github/workflows/codeql.yml"
assert_file_exists "${TEST_ROOT}/.github/dependabot.yml"
assert_file_exists "${TEST_ROOT}/scripts/tests/test_jira_next_recommendations.sh"
assert_contains "recommend-next" "${TEST_ROOT}/AGENTS.md"
assert_contains "recommend-next" "${TEST_ROOT}/docs/operations/jira-board-sync.md"
assert_contains "/rest/api/3/search/jql" "${TEST_ROOT}/docs/operations/jira-board-sync.md"
assert_contains "jira_board_recommend_next" "${TEST_ROOT}/scripts/task/jira-board.sh"
assert_contains "/rest/api/3/search/jql" "${TEST_ROOT}/scripts/task/jira-board.sh"
assert_contains "verify-pr-ready.sh" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "GitHub Actions Review Gate: PASS" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "STRICT_REQUIRE_GITHUB_ACTIONS_REVIEW_PASS" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "STRICT_REQUIRE_COMPANY_REVIEW_GATES" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "CTO Architecture Gate: PASS" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "QA Verification Gate: PASS" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "Product Value Gate: PASS" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "Final CTO Merge Gate: PASS" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "## Evidence" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "company_review_evidence_filter" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "User Decision" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "Architecture Reviewed" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "Commands Run" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "User Value" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "Prior Gates Checked" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "harness-tests shellcheck-reviewdog workflow-lint openapi-parse db-schema-coverage backend-check codeql-scan review-gate-pass" "${TEST_ROOT}/scripts/task/verify-pr-ready.sh"
assert_contains "jira_board_mark_done_for_task" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "Closes #" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "Jira: [" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "GitHub Actions Review Gate pass marker" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "CTO Architecture Gate" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "QA Verification Gate" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "Product Value Gate" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "Final CTO Merge Gate" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "evidence-backed" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "Feature continuity maintained" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "User decision recorded" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "STRICT_AUTO_FINISH_PR:-0" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "usage: post-role-review-pass.sh <PR_NUMBER> <GATE> <evidence_file>" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "evidence file is required" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "validate_evidence_file" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "require_evidence_entry" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "User Decision" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "Architecture Reviewed" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "Commands Run" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "User Value" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "Prior Gates Checked" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "review_marker=\"\$(company_review_marker \"\${gate}\")\"" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "CTO architecture and work breakdown" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "QA browser/API verification" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "Product/CBO value and retention review" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "Final CTO merge approval" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "test_quality_gate_contracts.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_docs_source_of_truth.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "db-schema-coverage" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "Verify ERD v0.8 schema coverage" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "db-schema-coverage" "${TEST_ROOT}/scripts/task/verify-pr-ready.sh"
assert_contains "CTO Architecture Gate" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "QA Verification Gate" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Product Value Gate" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Final CTO Merge Gate" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Evidence is mandatory" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Evidence entries must be filled in" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "작업 지속 및 사용자 결정 계약" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "User Decision" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Architecture Reviewed" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Commands Run" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "User Value" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Prior Gates Checked" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "reviewdog/action-shellcheck@v1" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "reviewdog/action-actionlint@v1" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "actions/github-script@v7" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "github/codeql-action/init@v3" "${TEST_ROOT}/.github/workflows/codeql.yml"
assert_contains "package-ecosystem: \"github-actions\"" "${TEST_ROOT}/.github/dependabot.yml"
assert_contains "validate-start" "${TEST_ROOT}/scripts/task/init-task.sh"
assert_contains "Once implementation starts" "${TEST_ROOT}/AGENTS.md"
assert_contains "Do not invent unrequested scope" "${TEST_ROOT}/AGENTS.md"
