#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/tests/testlib.sh
source "${SCRIPT_DIR}/testlib.sh"

for script in create-pr.sh verify-pr-ready.sh verify-coderabbit-review.sh run-coderabbit-review.sh post-coderabbit-addressed.sh verify-role-review-gates.sh verify-copilot-review.sh finish-pr.sh jira-board.sh post-role-review-pass.sh notify-pr-ready.sh mark-jira-done-from-pr.sh; do
  path="${TEST_ROOT}/scripts/task/${script}"
  assert_file_exists "${path}"
  bash -n "${path}"
done
bash -n "${TEST_ROOT}/scripts/hooks/commit-msg.sh"

assert_file_exists "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_file_exists "${TEST_ROOT}/.github/workflows/codeql.yml"
assert_file_exists "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_file_exists "${TEST_ROOT}/.github/dependabot.yml"
assert_file_exists "${TEST_ROOT}/scripts/tests/test_jira_next_recommendations.sh"
assert_file_exists "${TEST_ROOT}/scripts/tests/test_commit_convention.sh"
assert_contains "recommend-next" "${TEST_ROOT}/AGENTS.md"
assert_contains "recommend-next" "${TEST_ROOT}/docs/operations/jira-board-sync.md"
assert_contains "/rest/api/3/search/jql" "${TEST_ROOT}/docs/operations/jira-board-sync.md"
assert_contains "jira_board_recommend_next" "${TEST_ROOT}/scripts/task/jira-board.sh"
assert_contains "/rest/api/3/search/jql" "${TEST_ROOT}/scripts/task/jira-board.sh"
assert_contains "verify-pr-ready.sh" "${TEST_ROOT}/scripts/task/finish-pr.sh"

assert_contains "verify-coderabbit-review.sh" "${TEST_ROOT}/scripts/task/verify-pr-ready.sh"
assert_contains "verify-coderabbit-review.sh" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_not_contains "verify-copilot-review.sh" "${TEST_ROOT}/scripts/task/verify-pr-ready.sh"
assert_not_contains "verify-role-review-gates.sh" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "STRICT_REQUIRE_CODERABBIT_REVIEW" "${TEST_ROOT}/scripts/task/verify-coderabbit-review.sh"
assert_contains "CodeRabbit Subagent Review: PASS" "${TEST_ROOT}/scripts/task/verify-coderabbit-review.sh"
assert_contains "CodeRabbit Subagent Review: ADDRESSED" "${TEST_ROOT}/scripts/task/verify-coderabbit-review.sh"
assert_contains "리뷰 결과" "${TEST_ROOT}/scripts/task/verify-coderabbit-review.sh"
assert_contains "수정 범위" "${TEST_ROOT}/scripts/task/verify-coderabbit-review.sh"
assert_contains "coderabbit auth status --agent" "${TEST_ROOT}/scripts/task/run-coderabbit-review.sh"
assert_contains "baseRefName" "${TEST_ROOT}/scripts/task/run-coderabbit-review.sh"
assert_contains "coderabbit review --agent -t all --base" "${TEST_ROOT}/scripts/task/run-coderabbit-review.sh"
assert_contains "CodeRabbit Subagent Review: NEEDS_FIX" "${TEST_ROOT}/scripts/task/run-coderabbit-review.sh"
assert_contains "CodeRabbit raised 0 issues" "${TEST_ROOT}/scripts/task/run-coderabbit-review.sh"
assert_contains "usage: post-coderabbit-addressed.sh <PR_NUMBER> <evidence_file>" "${TEST_ROOT}/scripts/task/post-coderabbit-addressed.sh"
assert_contains "CodeRabbit Subagent Review: ADDRESSED" "${TEST_ROOT}/scripts/task/post-coderabbit-addressed.sh"
assert_contains "require_evidence_entry" "${TEST_ROOT}/scripts/task/post-coderabbit-addressed.sh"
assert_contains "test_coderabbit_review_gate.sh" "${TEST_ROOT}/scripts/tests/run.sh"

assert_contains "GitHub Actions Review Gate: PASS" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "STRICT_REQUIRE_GITHUB_ACTIONS_REVIEW_PASS" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "harness-tests shellcheck-reviewdog workflow-lint openapi-parse db-schema-coverage backend-check codeql-scan review-gate-pass" "${TEST_ROOT}/scripts/task/verify-pr-ready.sh"
assert_contains "STRICT_ALLOW_BLOCKED_FOR_AUTO_MERGE" "${TEST_ROOT}/scripts/task/verify-pr-ready.sh"
assert_contains "STRICT_ALLOW_BLOCKED_FOR_AUTO_MERGE=1" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "jira_board_mark_done_for_task" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "jira_board_mark_done_for_task" "${TEST_ROOT}/scripts/task/mark-jira-done-from-pr.sh"
assert_contains "GITHUB_EVENT_PATH" "${TEST_ROOT}/scripts/task/mark-jira-done-from-pr.sh"
assert_contains "codex/" "${TEST_ROOT}/scripts/task/mark-jira-done-from-pr.sh"
assert_contains "Jira-Key:" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "STRICT_REQUEST_COPILOT_REVIEW:-0" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "STRICT_COPILOT_REVIEW_REQUEST_REVIEWER:-@copilot" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "--add-reviewer" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "pull_request" "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_contains "types: [closed]" "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_contains "JIRA_EMAIL" "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_contains "JIRA_API_TOKEN" "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_contains "mark-jira-done-from-pr.sh" "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_contains "test_jira_auto_done_on_merge.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "validate_commit_subject \"\${title}\" \"PR title\"" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "validate_commit_subject \"\${pr_title}\" \"PR title\"" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "cleanup-merged" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "notify-pr-ready.sh" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "PR 자동 merge 및 정리 완료" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "gh pr merge \"\${pr}\" --merge" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "STUDYPOT_MM_WEBHOOK_URL" "${TEST_ROOT}/scripts/task/notify-pr-ready.sh"
assert_contains "STUDYPOT_MM_MENTIONS" "${TEST_ROOT}/scripts/task/notify-pr-ready.sh"
assert_contains "자동 merge가 완료" "${TEST_ROOT}/scripts/task/notify-pr-ready.sh"
assert_contains "scripts/task/finish-pr.sh" "${TEST_ROOT}/scripts/task/notify-pr-ready.sh"

assert_contains "Closes #" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "Jira: [" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "리뷰 게이트 체크리스트" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "최신 head에 GitHub Actions Review Gate PASS marker 게시" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "CodeRabbit subagent review 1회 실행" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "CodeRabbit Subagent Review PASS 또는 ADDRESSED marker" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_not_contains "최신 head에 Copilot review 수신 및 Copilot review thread 해결" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_not_contains "CTO Architecture Gate 증거 포함 marker" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "작업 연속성 유지" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "사용자 결정 기록" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "STRICT_AUTO_FINISH_PR:-0" "${TEST_ROOT}/scripts/task/create-pr.sh"

assert_contains "자동 merge" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "CodeRabbit Subagent Review" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "scripts/task/run-coderabbit-review.sh <PR_NUMBER>" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "scripts/task/post-coderabbit-addressed.sh <PR_NUMBER> <evidence_file>" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "verify-coderabbit-review.sh" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Copilot review는 기본 요청하지 않는다" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "CodeRabbit review gate" "${TEST_ROOT}/docs/testing/codex-harness.md"
assert_contains "STUDYPOT_MM_WEBHOOK_URL" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "finish-pr.sh cleanup-merged" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "GitHub merge 후 Jira Task는 자동으로 완료" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "GitHub merge 후 Jira Task는 자동으로 완료" "${TEST_ROOT}/docs/operations/jira-board-sync.md"
assert_contains "GitHub merge 버튼을 하드 블록" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "auto-merge PRs" "${TEST_ROOT}/AGENTS.md"
assert_contains "Mattermost notifications, PR bodies, PR review comments, and review evidence must be written in Korean" "${TEST_ROOT}/AGENTS.md"

assert_contains "usage: post-role-review-pass.sh <PR_NUMBER> <GATE> <evidence_file>" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "STRICT_REQUIRE_COMPANY_REVIEW_GATES" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "CTO Architecture Gate: PASS" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "QA Verification Gate: PASS" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "Product Value Gate: PASS" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "Final CTO Merge Gate: PASS" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "Legacy Role Gate Scripts" "${TEST_ROOT}/docs/operations/pr-review-gate.md"

assert_contains "test_auto_merge_notification.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_role_review_gate_validation.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_quality_gate_contracts.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_commit_convention.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_docs_source_of_truth.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_error_ledger_contracts.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_auth_api_contracts.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "db-schema-coverage" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "Verify ERD v0.8 schema coverage" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "db-schema-coverage" "${TEST_ROOT}/scripts/task/verify-pr-ready.sh"
assert_contains "reviewdog/action-shellcheck@v1" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "reviewdog/action-actionlint@v1" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "actions/github-script@v7" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "Verify CodeRabbit subagent review gate" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "verify-coderabbit-review.sh" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "github.event.pull_request.head.sha" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "issues: write" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "github/codeql-action/init@v3" "${TEST_ROOT}/.github/workflows/codeql.yml"
assert_contains "package-ecosystem: \"github-actions\"" "${TEST_ROOT}/.github/dependabot.yml"
assert_contains "validate-start" "${TEST_ROOT}/scripts/task/init-task.sh"
assert_contains "Once implementation starts" "${TEST_ROOT}/AGENTS.md"
assert_contains "Do not invent unrequested scope" "${TEST_ROOT}/AGENTS.md"
