#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/tests/testlib.sh
source "${SCRIPT_DIR}/testlib.sh"

compose="${TEST_ROOT}/deploy/rumiclean/docker-compose.yml"
env_example="${TEST_ROOT}/deploy/rumiclean/.env.example"
caddy_snippet="${TEST_ROOT}/deploy/rumiclean/Caddyfile.studypot"
deployment_doc="${TEST_ROOT}/docs/operations/deployment.md"
workflow="${TEST_ROOT}/.github/workflows/deploy.yml"
application_config="${TEST_ROOT}/src/main/resources/application.yml"

assert_contains "test_rumiclean_migration_contracts.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_file_exists "${compose}"
assert_file_exists "${env_example}"
assert_file_exists "${caddy_snippet}"
assert_file_exists "${application_config}"

assert_contains "studypot-api:" "${compose}"
assert_contains "studypot-mysql:" "${compose}"
assert_contains "studypot-redis:" "${compose}"
assert_contains "studypot-rabbitmq:" "${compose}"
assert_contains "mysql:8.0" "${compose}"
assert_contains "redis:7-alpine" "${compose}"
assert_contains "rabbitmq:4-management" "${compose}"
assert_contains "container_name: studypot-api" "${compose}"
assert_contains "container_name: studypot-mysql" "${compose}"
assert_contains "container_name: studypot-redis" "${compose}"
assert_contains "container_name: studypot-rabbitmq" "${compose}"
assert_contains "compose-cleanb_default" "${compose}"
assert_contains "external: true" "${compose}"
assert_contains "STUDYPOT_REDIS_HOST: studypot-redis" "${compose}"
assert_contains "STUDYPOT_RABBITMQ_HOST: studypot-rabbitmq" "${compose}"
assert_contains "STUDYPOT_MYSQL_JDBC_PARAMS" "${compose}"
assert_contains "127.0.0.1:\${STUDYPOT_HTTP_PORT:-8080}:8080" "${compose}"
assert_contains "STUDYPOT_RATE_LIMIT_ENABLED" "${compose}"
assert_contains "STUDYPOT_NOTIFICATION_RABBITMQ_ENABLED" "${compose}"
assert_contains "STUDYPOT_REDIS_HEALTH_ENABLED" "${compose}"
assert_contains "STUDYPOT_RABBITMQ_HEALTH_ENABLED" "${compose}"
assert_contains "MYSQL_ROOT_PASSWORD" "${compose}"
assert_contains "RABBITMQ_DEFAULT_USER" "${compose}"
assert_contains "RABBITMQ_DEFAULT_PASS" "${compose}"
assert_contains "STUDYPOT_RABBITMQ_ERL_ARGS:-+S 1:1" "${compose}"
assert_contains "redis-cli" "${compose}"
assert_contains "rabbitmq-diagnostics" "${compose}"
assert_contains "/actuator/health" "${compose}"
assert_not_contains "vm_memory_high_watermark.relative" "${compose}"
assert_not_contains "0.0.0.0:3306" "${compose}"
assert_not_contains "0.0.0.0:6379" "${compose}"
assert_not_contains "0.0.0.0:5672" "${compose}"
assert_not_contains "0.0.0.0:15672" "${compose}"
assert_not_contains "0.0.0.0:8080" "${compose}"

assert_contains "studypot.rumiclean.com" "${caddy_snippet}"
assert_contains "reverse_proxy studypot-api:8080" "${caddy_snippet}"

assert_contains "STUDYPOT_IMAGE=" "${env_example}"
assert_contains "STUDYPOT_HTTP_PORT=8080" "${env_example}"
assert_contains "STUDYPOT_MYSQL_ROOT_PASSWORD=" "${env_example}"
assert_contains "STUDYPOT_MYSQL_JDBC_PARAMS=" "${env_example}"
assert_contains "SPRING_DATASOURCE_PASSWORD=" "${env_example}"
assert_contains "STUDYPOT_REDIS_PASSWORD=" "${env_example}"
assert_contains "STUDYPOT_RABBITMQ_PASSWORD=" "${env_example}"
assert_contains "STUDYPOT_RABBITMQ_ERL_ARGS=" "${env_example}"
assert_contains "STUDYPOT_AUTH_JWT_ISSUER=https://studypot.rumiclean.com" "${env_example}"
assert_contains "STUDYPOT_AUTH_OAUTH2_BACKEND_CALLBACK_URI=https://studypot.rumiclean.com/api/login/oauth2/code/google" "${env_example}"
assert_contains "STUDYPOT_AUTH_OAUTH2_FRONTEND_SUCCESS_URI=https://studypot.netlify.app/auth/success" "${env_example}"
assert_contains "STUDYPOT_AUTH_OAUTH2_FRONTEND_FAILURE_URI=https://studypot.netlify.app/auth/failure" "${env_example}"
assert_contains "STUDYPOT_CORS_ALLOWED_ORIGINS=https://studypot.netlify.app,https://studypot.rumiclean.com" "${env_example}"
assert_contains "STUDYPOT_GOOGLE_CLIENT_ID=" "${env_example}"
assert_contains "STUDYPOT_GOOGLE_CLIENT_SECRET=" "${env_example}"
assert_contains "client-id: \${STUDYPOT_GOOGLE_CLIENT_ID:}" "${application_config}"
assert_contains "client-secret: \${STUDYPOT_GOOGLE_CLIENT_SECRET:}" "${application_config}"
assert_contains "STUDYPOT_AI_OPENAI_CONNECT_TIMEOUT=5s" "${env_example}"
assert_contains "STUDYPOT_AI_OPENAI_READ_TIMEOUT=120s" "${env_example}"
assert_contains "STUDYPOT_AI_OPENAI_MODEL_DETAIL_KEYWORD_SUGGEST=" "${env_example}"
assert_contains "STUDYPOT_AI_OPENAI_MAX_OUTPUT_TOKENS_DETAIL_KEYWORD_SUGGEST=256" "${env_example}"
assert_contains "STUDYPOT_AI_OPENAI_MAX_OUTPUT_TOKENS_CURRICULUM_GENERATE=4096" "${env_example}"
assert_contains "STUDYPOT_AI_OPENAI_MAX_OUTPUT_TOKENS_RETROSPECTIVE_FEEDBACK=2048" "${env_example}"
assert_contains "STUDYPOT_AI_OPENAI_MAX_OUTPUT_TOKENS_TEAM_LEAD_CHAT=1536" "${env_example}"
assert_contains "STUDYPOT_AI_OPENAI_CONNECT_TIMEOUT: \"\${STUDYPOT_AI_OPENAI_CONNECT_TIMEOUT:-5s}\"" "${compose}"
assert_contains "STUDYPOT_AI_OPENAI_READ_TIMEOUT: \"\${STUDYPOT_AI_OPENAI_READ_TIMEOUT:-120s}\"" "${compose}"
assert_contains "STUDYPOT_AI_OPENAI_MODEL_DETAIL_KEYWORD_SUGGEST: \"\${STUDYPOT_AI_OPENAI_MODEL_DETAIL_KEYWORD_SUGGEST:-}\"" "${compose}"
assert_contains "STUDYPOT_AI_OPENAI_MAX_OUTPUT_TOKENS_CURRICULUM_GENERATE: \"\${STUDYPOT_AI_OPENAI_MAX_OUTPUT_TOKENS_CURRICULUM_GENERATE:-4096}\"" "${compose}"
assert_contains "STUDYPOT_AI_OPENAI_MAX_OUTPUT_TOKENS_TEAM_LEAD_CHAT: \"\${STUDYPOT_AI_OPENAI_MAX_OUTPUT_TOKENS_TEAM_LEAD_CHAT:-1536}\"" "${compose}"

assert_contains "STUDYPOT_DEPLOY_COMPOSE_FILE" "${workflow}"
assert_contains "deploy/docker-compose.prod.yml" "${workflow}"
assert_contains "STUDYPOT_AUTH_OAUTH2_FRONTEND_SUCCESS_URI: \${{ secrets.STUDYPOT_AUTH_OAUTH2_FRONTEND_SUCCESS_URI }}" "${workflow}"
assert_contains "STUDYPOT_AUTH_OAUTH2_FRONTEND_FAILURE_URI: \${{ secrets.STUDYPOT_AUTH_OAUTH2_FRONTEND_FAILURE_URI }}" "${workflow}"
assert_contains "STUDYPOT_CORS_ALLOWED_ORIGINS: \${{ secrets.STUDYPOT_CORS_ALLOWED_ORIGINS }}" "${workflow}"
assert_contains "printf 'STUDYPOT_CORS_ALLOWED_ORIGINS=%s\\n' \"\${STUDYPOT_CORS_ALLOWED_ORIGINS}\"" "${workflow}"
assert_contains "scp -i" "${workflow}"

assert_contains "rumiclean 전체 이관" "${deployment_doc}"
assert_contains "/home/ec2-user/compose-studypot" "${deployment_doc}"
assert_contains "studypot.rumiclean.com" "${deployment_doc}"
assert_contains "Oracle 배포는 rollback" "${deployment_doc}"
assert_contains "mysqldump" "${deployment_doc}"
assert_contains "STUDYPOT_MYSQL_JDBC_PARAMS" "${deployment_doc}"
assert_contains "flyway_schema_history" "${deployment_doc}"
assert_contains "studypot-redis" "${deployment_doc}"
assert_contains "studypot-rabbitmq" "${deployment_doc}"
assert_contains "STUDYPOT_RABBITMQ_ERL_ARGS" "${deployment_doc}"
assert_contains "STUDYPOT_HTTP_PORT" "${deployment_doc}"
assert_contains "Caddyfile.studypot" "${deployment_doc}"

for file in "${compose}" "${env_example}" "${caddy_snippet}" "${deployment_doc}" "${workflow}"; do
  assert_not_contains "studypot1234" "${file}"
  assert_not_contains "GOCSPX-" "${file}"
  assert_not_contains "sk-" "${file}"
  assert_not_contains "amqps://" "${file}"
done
