#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/tests/testlib.sh
source "${SCRIPT_DIR}/testlib.sh"

for script in create-pr.sh verify-pr-ready.sh verify-role-review-gates.sh finish-pr.sh jira-board.sh post-role-review-pass.sh notify-pr-ready.sh mark-jira-done-from-pr.sh; do
  path="${TEST_ROOT}/scripts/task/${script}"
  assert_file_exists "${path}"
  bash -n "${path}"
done
bash -n "${TEST_ROOT}/scripts/hooks/commit-msg.sh"

assert_file_exists "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_file_exists "${TEST_ROOT}/.github/workflows/codeql.yml"
assert_file_exists "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_file_exists "${TEST_ROOT}/.github/dependabot.yml"
assert_file_exists "${TEST_ROOT}/scripts/tests/test_jira_next_recommendations.sh"
assert_file_exists "${TEST_ROOT}/scripts/tests/test_commit_convention.sh"
assert_contains "recommend-next" "${TEST_ROOT}/AGENTS.md"
assert_contains "recommend-next" "${TEST_ROOT}/docs/operations/jira-board-sync.md"
assert_contains "/rest/api/3/search/jql" "${TEST_ROOT}/docs/operations/jira-board-sync.md"
assert_contains "jira_board_recommend_next" "${TEST_ROOT}/scripts/task/jira-board.sh"
assert_contains "/rest/api/3/search/jql" "${TEST_ROOT}/scripts/task/jira-board.sh"
assert_contains "verify-pr-ready.sh" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "GitHub Actions Review Gate: PASS" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "STRICT_REQUIRE_GITHUB_ACTIONS_REVIEW_PASS" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "verify-role-review-gates.sh" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "STRICT_REQUIRE_COMPANY_REVIEW_GATES" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "CTO Architecture Gate: PASS" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "QA Verification Gate: PASS" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "Product Value Gate: PASS" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "Final CTO Merge Gate: PASS" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "## 증거" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "company_review_required_labels" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "사용자 결정" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "아키텍처 검토" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "실행한 명령" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "사용자 가치" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "이전 게이트 확인" "${TEST_ROOT}/scripts/task/verify-role-review-gates.sh"
assert_contains "harness-tests shellcheck-reviewdog workflow-lint openapi-parse db-schema-coverage backend-check codeql-scan review-gate-pass" "${TEST_ROOT}/scripts/task/verify-pr-ready.sh"
assert_contains "STRICT_ALLOW_BLOCKED_FOR_MANUAL_MERGE" "${TEST_ROOT}/scripts/task/verify-pr-ready.sh"
assert_contains "STRICT_ALLOW_BLOCKED_FOR_MANUAL_MERGE=1" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "jira_board_mark_done_for_task" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "jira_board_mark_done_for_task" "${TEST_ROOT}/scripts/task/mark-jira-done-from-pr.sh"
assert_contains "GITHUB_EVENT_PATH" "${TEST_ROOT}/scripts/task/mark-jira-done-from-pr.sh"
assert_contains "codex/" "${TEST_ROOT}/scripts/task/mark-jira-done-from-pr.sh"
assert_contains "Jira-Key:" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "pull_request" "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_contains "types: [closed]" "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_contains "JIRA_EMAIL" "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_contains "JIRA_API_TOKEN" "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_contains "mark-jira-done-from-pr.sh" "${TEST_ROOT}/.github/workflows/jira-auto-done.yml"
assert_contains "test_jira_auto_done_on_merge.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "validate_commit_subject \"\${title}\" \"PR title\"" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "validate_commit_subject \"\${pr_title}\" \"PR title\"" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "cleanup-merged" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "notify-pr-ready.sh" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "PR 수동 merge 준비 완료" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_not_contains "gh pr merge \"\${pr}\" --merge" "${TEST_ROOT}/scripts/task/finish-pr.sh"
assert_contains "STUDYPOT_MM_WEBHOOK_URL" "${TEST_ROOT}/scripts/task/notify-pr-ready.sh"
assert_contains "STUDYPOT_MM_MENTIONS" "${TEST_ROOT}/scripts/task/notify-pr-ready.sh"
assert_contains "수동 merge 준비" "${TEST_ROOT}/scripts/task/notify-pr-ready.sh"
assert_contains "직접 merge 버튼" "${TEST_ROOT}/scripts/task/notify-pr-ready.sh"
assert_contains "scripts/task/finish-pr.sh cleanup-merged" "${TEST_ROOT}/scripts/task/notify-pr-ready.sh"
assert_contains "Closes #" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "Jira: [" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "리뷰 게이트 체크리스트" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "최신 head에 GitHub Actions Review Gate PASS marker 게시" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "CTO Architecture Gate" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "QA Verification Gate" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "Product Value Gate" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "Final CTO Merge Gate" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "증거 포함" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "작업 연속성 유지" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "사용자 결정 기록" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "STRICT_AUTO_FINISH_PR:-0" "${TEST_ROOT}/scripts/task/create-pr.sh"
assert_contains "수동 merge 알림" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "STUDYPOT_MM_WEBHOOK_URL" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "finish-pr.sh cleanup-merged" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "GitHub merge 후 Jira Task는 자동으로 완료" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "GitHub merge 후 Jira Task는 자동으로 완료" "${TEST_ROOT}/docs/operations/jira-board-sync.md"
assert_contains "GitHub merge 버튼을 하드 블록" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Do not auto-merge PRs" "${TEST_ROOT}/AGENTS.md"
assert_contains "Mattermost notifications, PR bodies, PR review comments, and role gate evidence must be written in Korean" "${TEST_ROOT}/AGENTS.md"
assert_contains "usage: post-role-review-pass.sh <PR_NUMBER> <GATE> <evidence_file>" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "증거 파일이 필요합니다" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "validate_evidence_file" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "require_evidence_entry" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "사용자 결정" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "아키텍처 검토" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "실행한 명령" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "사용자 가치" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "이전 게이트 확인" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "review_marker=\"\$(company_review_marker \"\${gate}\")\"" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "CTO 아키텍처 및 작업 분해" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "QA 브라우저/API 검증" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "Product/CBO 가치 및 리텐션 검토" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "Final CTO merge 승인" "${TEST_ROOT}/scripts/task/post-role-review-pass.sh"
assert_contains "test_manual_merge_notification.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_role_review_gate_validation.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_quality_gate_contracts.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_commit_convention.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_docs_source_of_truth.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_error_ledger_contracts.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "test_auth_api_contracts.sh" "${TEST_ROOT}/scripts/tests/run.sh"
assert_contains "db-schema-coverage" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "Verify ERD v0.8 schema coverage" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "db-schema-coverage" "${TEST_ROOT}/scripts/task/verify-pr-ready.sh"
assert_contains "CTO Architecture Gate" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "QA Verification Gate" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Product Value Gate" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "Final CTO Merge Gate" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "증거는 모든 role gate에 필수" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "증거 항목은 반드시 채워야 한다" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "작업 지속 및 사용자 결정 계약" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "사용자 결정" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "아키텍처 검토" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "실행한 명령" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "사용자 가치" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "이전 게이트 확인" "${TEST_ROOT}/docs/operations/pr-review-gate.md"
assert_contains "reviewdog/action-shellcheck@v1" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "reviewdog/action-actionlint@v1" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "actions/github-script@v7" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "Verify company role review gates" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "verify-role-review-gates.sh" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "github.event.pull_request.head.sha" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "issues: write" "${TEST_ROOT}/.github/workflows/pr-quality.yml"
assert_contains "github/codeql-action/init@v3" "${TEST_ROOT}/.github/workflows/codeql.yml"
assert_contains "package-ecosystem: \"github-actions\"" "${TEST_ROOT}/.github/dependabot.yml"
assert_contains "validate-start" "${TEST_ROOT}/scripts/task/init-task.sh"
assert_contains "Once implementation starts" "${TEST_ROOT}/AGENTS.md"
assert_contains "Do not invent unrequested scope" "${TEST_ROOT}/AGENTS.md"
