package com.studypot.aistudyleader.notification.domain;

public enum NotificationType {
	GROUP_INVITE_CREATED,
	ONBOARDING_REQUESTED,
	ONBOARDING_SUBMITTED,
	ONBOARDING_COMPLETED,
	STUDY_STARTED,
	WEEK_STARTED,
	TASK_DUE_REMINDER,
	TASK_OVERDUE_CHECK,
	INCOMPLETE_REASON_REQUESTED,
	RETROSPECTIVE_READY,
	RETROSPECTIVE_REMINDER,
	NEXT_WEEK_ADJUSTED
}
