-- AI Study Leader DB Schema v1
-- Source: ERD v0.8 MySQL8, Requirements v0.3, CR-20260504-no-discord-inapp-notification
-- IDs are application-generated UUIDv7 values stored as BINARY(16).

create table users (
  id binary(16) not null,
  email varchar(320) not null,
  email_live_key varchar(320) not null,
  nickname varchar(80) not null,
  profile_image text null,
  bio text null,
  interests json null,
  skill_level varchar(40) null,
  last_login_at timestamp(6) null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  deleted_at timestamp(6) null,
  primary key (id),
  unique key users_email_live_uidx (email_live_key),
  constraint users_skill_level_check check (skill_level is null or skill_level in ('beginner','intermediate','advanced'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table oauth_account (
  id binary(16) not null,
  user_id binary(16) not null,
  provider varchar(40) not null,
  provider_user_id varchar(191) not null,
  provider_account_live_key varchar(255) not null,
  email varchar(320) null,
  access_token_enc text null,
  refresh_token_enc text null,
  token_expires_at timestamp(6) null,
  scope varchar(1000) null,
  connected_at timestamp(6) not null default current_timestamp(6),
  last_synced_at timestamp(6) null,
  deleted_at timestamp(6) null,
  primary key (id),
  unique key oauth_provider_account_live_uidx (provider_account_live_key),
  key oauth_user_idx (user_id),
  constraint oauth_account_user_fk foreign key (user_id) references users (id),
  constraint oauth_provider_check check (provider in ('GOOGLE'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table refresh_token (
  id binary(16) not null,
  user_id binary(16) not null,
  token_hash varchar(128) not null,
  device_info varchar(255) null,
  ip_address varchar(45) null,
  expires_at timestamp(6) not null,
  revoked_at timestamp(6) null,
  created_at timestamp(6) not null default current_timestamp(6),
  primary key (id),
  unique key refresh_token_hash_uidx (token_hash),
  key refresh_token_user_idx (user_id),
  constraint refresh_token_user_fk foreign key (user_id) references users (id) on delete cascade
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table study_group (
  id binary(16) not null,
  created_by binary(16) not null,
  name varchar(120) not null,
  description text null,
  topic varchar(120) not null,
  detail_keywords json not null,
  level varchar(40) null,
  status varchar(40) not null,
  max_members int not null,
  is_public tinyint(1) not null default 0,
  invite_code varchar(80) not null,
  starts_at date not null,
  ends_at date not null,
  onboarding_started_at timestamp(6) null,
  started_at timestamp(6) null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  deleted_at timestamp(6) null,
  primary key (id),
  unique key study_group_invite_code_uidx (invite_code),
  key study_group_created_by_idx (created_by),
  key study_group_status_idx (status),
  constraint study_group_created_by_fk foreign key (created_by) references users (id),
  constraint study_group_status_check check (status in ('DRAFT','ONBOARDING','ACTIVE','COMPLETED','ARCHIVED')),
  constraint study_group_max_members_check check (max_members > 0),
  constraint study_group_period_check check (ends_at >= starts_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table group_member (
  id binary(16) not null,
  group_id binary(16) not null,
  user_id binary(16) not null,
  permission varchar(40) not null,
  status varchar(40) not null,
  display_name varchar(80) null,
  joined_at timestamp(6) not null default current_timestamp(6),
  activated_at timestamp(6) null,
  left_at timestamp(6) null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  deleted_at timestamp(6) null,
  primary key (id),
  unique key group_member_group_user_uidx (group_id, user_id),
  key group_member_user_idx (user_id),
  key group_member_group_status_idx (group_id, status),
  constraint group_member_group_fk foreign key (group_id) references study_group (id),
  constraint group_member_user_fk foreign key (user_id) references users (id),
  constraint group_member_permission_check check (permission in ('OWNER','MEMBER')),
  constraint group_member_status_check check (status in ('PENDING_ONBOARDING','ACTIVE','LEFT'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table group_onboarding_response (
  id binary(16) not null,
  group_id binary(16) not null,
  member_id binary(16) not null,
  keyword_skill_levels json not null,
  task_preferences json not null,
  additional_note text null,
  status varchar(40) not null,
  submitted_at timestamp(6) null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  deleted_at timestamp(6) null,
  primary key (id),
  unique key onboarding_member_uidx (member_id),
  key onboarding_group_status_idx (group_id, status),
  constraint onboarding_group_fk foreign key (group_id) references study_group (id),
  constraint onboarding_member_fk foreign key (member_id) references group_member (id),
  constraint onboarding_status_check check (status in ('DRAFT','SUBMITTED'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table member_availability_slot (
  id binary(16) not null,
  onboarding_response_id binary(16) not null,
  member_id binary(16) not null,
  day_of_week tinyint not null,
  start_time time not null,
  end_time time not null,
  timezone varchar(80) not null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  deleted_at timestamp(6) null,
  primary key (id),
  key availability_response_idx (onboarding_response_id),
  key availability_member_day_idx (member_id, day_of_week),
  constraint availability_response_fk foreign key (onboarding_response_id) references group_onboarding_response (id),
  constraint availability_member_fk foreign key (member_id) references group_member (id),
  constraint availability_day_check check (day_of_week between 0 and 6),
  constraint availability_time_check check (end_time > start_time)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table group_rule (
  id binary(16) not null,
  group_id binary(16) not null,
  created_by binary(16) not null,
  rule_type varchar(60) not null,
  config json not null,
  description text null,
  is_active tinyint(1) not null default 1,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  deleted_at timestamp(6) null,
  primary key (id),
  key group_rule_group_type_idx (group_id, rule_type),
  key group_rule_created_by_idx (created_by),
  constraint group_rule_group_fk foreign key (group_id) references study_group (id),
  constraint group_rule_created_by_fk foreign key (created_by) references users (id),
  constraint group_rule_type_check check (rule_type in ('TASK_DEADLINE','RETROSPECTIVE_REQUIRED','CUSTOM_NOTE'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table curriculum (
  id binary(16) not null,
  group_id binary(16) not null,
  llm_usage_id binary(16) null,
  title varchar(160) not null,
  total_weeks int not null,
  onboarding_summary json null,
  generated_by_ai tinyint(1) not null default 0,
  generation_prompt text null,
  status varchar(40) not null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  deleted_at timestamp(6) null,
  primary key (id),
  unique key curriculum_group_uidx (group_id),
  key curriculum_status_idx (status),
  key curriculum_llm_usage_idx (llm_usage_id),
  constraint curriculum_group_fk foreign key (group_id) references study_group (id),
  constraint curriculum_status_check check (status in ('DRAFT','ACTIVE','COMPLETED')),
  constraint curriculum_total_weeks_check check (total_weeks > 0)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table curriculum_week (
  id binary(16) not null,
  curriculum_id binary(16) not null,
  week_number int not null,
  title varchar(160) not null,
  description text null,
  sprint_goal text null,
  learning_goals json null,
  resources json null,
  status varchar(40) not null,
  starts_at timestamp(6) not null,
  ends_at timestamp(6) not null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  deleted_at timestamp(6) null,
  primary key (id),
  unique key curriculum_week_number_uidx (curriculum_id, week_number),
  key curriculum_week_status_idx (curriculum_id, status),
  constraint curriculum_week_curriculum_fk foreign key (curriculum_id) references curriculum (id),
  constraint curriculum_week_status_check check (status in ('PENDING','IN_PROGRESS','COMPLETED')),
  constraint curriculum_week_number_check check (week_number > 0),
  constraint curriculum_week_window_check check (ends_at > starts_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table weekly_task (
  id binary(16) not null,
  curriculum_week_id binary(16) not null,
  display_order int not null,
  task_type varchar(40) not null,
  title varchar(200) not null,
  description text null,
  required tinyint(1) not null default 1,
  due_at timestamp(6) null,
  generated_by_ai tinyint(1) not null default 0,
  source_payload json null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  deleted_at timestamp(6) null,
  primary key (id),
  unique key weekly_task_order_uidx (curriculum_week_id, display_order),
  key weekly_task_week_type_idx (curriculum_week_id, task_type),
  constraint weekly_task_week_fk foreign key (curriculum_week_id) references curriculum_week (id),
  constraint weekly_task_type_check check (task_type in ('READING','PRACTICE','ASSIGNMENT','PROJECT','CUSTOM')),
  constraint weekly_task_display_order_check check (display_order > 0)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table member_week_progress (
  id binary(16) not null,
  curriculum_week_id binary(16) not null,
  member_id binary(16) not null,
  status varchar(40) not null,
  started_at timestamp(6) null,
  due_at timestamp(6) null,
  completed_at timestamp(6) null,
  completion_note text null,
  incomplete_reason text null,
  reason_submitted_at timestamp(6) null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  primary key (id),
  unique key member_week_progress_uidx (curriculum_week_id, member_id),
  key member_week_progress_member_idx (member_id, status),
  constraint member_week_progress_week_fk foreign key (curriculum_week_id) references curriculum_week (id),
  constraint member_week_progress_member_fk foreign key (member_id) references group_member (id),
  constraint member_week_progress_status_check check (status in ('NOT_STARTED','IN_PROGRESS','COMPLETED','INCOMPLETE','FEEDBACK_READY'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table task_completion (
  id binary(16) not null,
  progress_id binary(16) not null,
  weekly_task_id binary(16) not null,
  member_id binary(16) not null,
  status varchar(40) not null,
  due_at timestamp(6) null,
  completed_at timestamp(6) null,
  completion_note text null,
  incomplete_reason text null,
  reason_submitted_at timestamp(6) null,
  evidence_url text null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  primary key (id),
  unique key task_completion_task_member_uidx (weekly_task_id, member_id),
  key task_completion_progress_idx (progress_id),
  key task_completion_member_status_due_idx (member_id, status, due_at),
  constraint task_completion_progress_fk foreign key (progress_id) references member_week_progress (id),
  constraint task_completion_task_fk foreign key (weekly_task_id) references weekly_task (id),
  constraint task_completion_member_fk foreign key (member_id) references group_member (id),
  constraint task_completion_status_check check (status in ('TODO','DONE','INCOMPLETE','SKIPPED'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table rule_violation (
  id binary(16) not null,
  rule_id binary(16) not null,
  member_id binary(16) not null,
  task_completion_id binary(16) null,
  details json null,
  status varchar(40) not null,
  resolved_at timestamp(6) null,
  resolved_note text null,
  occurred_at timestamp(6) not null,
  created_at timestamp(6) not null default current_timestamp(6),
  primary key (id),
  key rule_violation_rule_idx (rule_id, status),
  key rule_violation_member_idx (member_id, status),
  key rule_violation_task_completion_idx (task_completion_id),
  constraint rule_violation_rule_fk foreign key (rule_id) references group_rule (id),
  constraint rule_violation_member_fk foreign key (member_id) references group_member (id),
  constraint rule_violation_task_completion_fk foreign key (task_completion_id) references task_completion (id),
  constraint rule_violation_status_check check (status in ('OPEN','RESOLVED','WAIVED'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table llm_usage (
  id binary(16) not null,
  user_id binary(16) null,
  group_id binary(16) null,
  purpose varchar(80) not null,
  provider varchar(40) not null,
  model varchar(120) not null,
  input_tokens int not null default 0,
  output_tokens int not null default 0,
  total_cost_usd decimal(12,6) null,
  latency_ms int null,
  status varchar(40) not null,
  error_code varchar(80) null,
  request_payload json null,
  response_summary text null,
  created_date_utc date not null,
  created_at timestamp(6) not null default current_timestamp(6),
  primary key (id),
  key llm_usage_group_date_idx (group_id, created_date_utc),
  key llm_usage_user_date_idx (user_id, created_date_utc),
  key llm_usage_purpose_status_idx (purpose, status),
  constraint llm_usage_user_fk foreign key (user_id) references users (id),
  constraint llm_usage_group_fk foreign key (group_id) references study_group (id),
  constraint llm_usage_provider_check check (provider in ('OPENAI','ANTHROPIC')),
  constraint llm_usage_status_check check (status in ('SUCCESS','FAILED','TIMEOUT'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

alter table curriculum
  add constraint curriculum_llm_usage_fk foreign key (llm_usage_id) references llm_usage (id);

create table retrospective (
  id binary(16) not null,
  progress_id binary(16) not null,
  curriculum_week_id binary(16) not null,
  member_id binary(16) not null,
  llm_usage_id binary(16) null,
  trigger_type varchar(60) not null,
  input_summary json null,
  ai_feedback json null,
  next_week_adjustment json null,
  status varchar(40) not null,
  requested_at timestamp(6) not null default current_timestamp(6),
  completed_at timestamp(6) null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  primary key (id),
  key retrospective_progress_idx (progress_id),
  key retrospective_week_member_idx (curriculum_week_id, member_id),
  key retrospective_llm_usage_idx (llm_usage_id),
  constraint retrospective_progress_fk foreign key (progress_id) references member_week_progress (id),
  constraint retrospective_week_fk foreign key (curriculum_week_id) references curriculum_week (id),
  constraint retrospective_member_fk foreign key (member_id) references group_member (id),
  constraint retrospective_llm_usage_fk foreign key (llm_usage_id) references llm_usage (id),
  constraint retrospective_trigger_check check (trigger_type in ('WEEK_ENDED','INCOMPLETE_MODAL','USER_CHAT','MANUAL')),
  constraint retrospective_status_check check (status in ('PENDING','PROCESSING','COMPLETED','FAILED'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table ai_conversation (
  id binary(16) not null,
  group_id binary(16) not null,
  member_id binary(16) not null,
  curriculum_week_id binary(16) null,
  retrospective_id binary(16) null,
  conversation_type varchar(60) not null,
  status varchar(40) not null,
  summary text null,
  opened_at timestamp(6) not null default current_timestamp(6),
  closed_at timestamp(6) null,
  created_at timestamp(6) not null default current_timestamp(6),
  updated_at timestamp(6) not null default current_timestamp(6) on update current_timestamp(6),
  primary key (id),
  key ai_conversation_group_idx (group_id, status),
  key ai_conversation_member_idx (member_id, status),
  key ai_conversation_week_idx (curriculum_week_id),
  key ai_conversation_retrospective_idx (retrospective_id),
  constraint ai_conversation_group_fk foreign key (group_id) references study_group (id),
  constraint ai_conversation_member_fk foreign key (member_id) references group_member (id),
  constraint ai_conversation_week_fk foreign key (curriculum_week_id) references curriculum_week (id),
  constraint ai_conversation_retrospective_fk foreign key (retrospective_id) references retrospective (id),
  constraint ai_conversation_type_check check (conversation_type in ('TEAM_LEAD_CHAT','RETROSPECTIVE')),
  constraint ai_conversation_status_check check (status in ('OPEN','CLOSED'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table ai_conversation_message (
  id binary(16) not null,
  conversation_id binary(16) not null,
  llm_usage_id binary(16) null,
  sender_type varchar(40) not null,
  content text not null,
  metadata json null,
  created_at timestamp(6) not null default current_timestamp(6),
  primary key (id),
  key ai_message_conversation_idx (conversation_id, created_at),
  key ai_message_llm_usage_idx (llm_usage_id),
  constraint ai_message_conversation_fk foreign key (conversation_id) references ai_conversation (id),
  constraint ai_message_llm_usage_fk foreign key (llm_usage_id) references llm_usage (id),
  constraint ai_message_sender_check check (sender_type in ('USER','ASSISTANT','SYSTEM'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table notification (
  id binary(16) not null,
  group_id binary(16) not null,
  recipient_user_id binary(16) not null,
  related_onboarding_response_id binary(16) null,
  related_week_id binary(16) null,
  related_task_completion_id binary(16) null,
  related_retrospective_id binary(16) null,
  notification_type varchar(80) not null,
  channel varchar(60) not null,
  idempotency_key varchar(191) not null,
  title varchar(160) not null,
  body text null,
  payload json not null,
  status varchar(40) not null,
  delivered_at timestamp(6) null,
  read_at timestamp(6) null,
  error_message text null,
  retry_count int not null default 0,
  scheduled_at timestamp(6) null,
  created_at timestamp(6) not null default current_timestamp(6),
  primary key (id),
  unique key notification_idempotency_uidx (idempotency_key),
  key notification_group_status_scheduled_idx (group_id, status, scheduled_at),
  key notification_recipient_status_idx (recipient_user_id, status, read_at, created_at),
  key notification_onboarding_idx (related_onboarding_response_id),
  key notification_week_idx (related_week_id),
  key notification_task_completion_idx (related_task_completion_id),
  key notification_retrospective_idx (related_retrospective_id),
  constraint notification_group_fk foreign key (group_id) references study_group (id),
  constraint notification_recipient_user_fk foreign key (recipient_user_id) references users (id),
  constraint notification_onboarding_fk foreign key (related_onboarding_response_id) references group_onboarding_response (id),
  constraint notification_week_fk foreign key (related_week_id) references curriculum_week (id),
  constraint notification_task_completion_fk foreign key (related_task_completion_id) references task_completion (id),
  constraint notification_retrospective_fk foreign key (related_retrospective_id) references retrospective (id),
  constraint notification_channel_check check (channel in ('IN_APP')),
  constraint notification_status_check check (status in ('PENDING','DELIVERED','READ','FAILED','SKIPPED')),
  constraint notification_retry_count_check check (retry_count >= 0)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;
