-- AI Study Leader DB Schema v1
-- Source of truth: docs/specs/domain-erd.md and docs/specs/db-contract-v1.md
-- This is a migration-ready draft. It is not executed by the planning package.
-- UUIDv7 values are generated by Spring application code before insert.

create extension if not exists citext;

create table users (
  id uuid primary key,
  email citext,
  display_name varchar(80) not null,
  avatar_url text,
  timezone varchar(64) not null default 'Asia/Seoul',
  status varchar(20) not null default 'active',
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint users_status_check check (status in ('active', 'inactive', 'blocked'))
);

create unique index users_email_active_uidx
  on users (lower(email::text))
  where email is not null and deleted_at is null;

create table user_oauth_accounts (
  id uuid primary key,
  user_id uuid not null references users(id) on delete restrict,
  provider varchar(30) not null,
  provider_user_id varchar(160) not null,
  provider_email citext,
  provider_profile jsonb not null default '{}'::jsonb,
  linked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index user_oauth_accounts_provider_subject_active_uidx
  on user_oauth_accounts (provider, provider_user_id)
  where deleted_at is null;
create index user_oauth_accounts_user_id_idx
  on user_oauth_accounts (user_id)
  where deleted_at is null;

create table user_discord_accounts (
  id uuid primary key,
  user_id uuid not null references users(id) on delete restrict,
  discord_user_id varchar(40) not null,
  username varchar(80),
  global_name varchar(80),
  avatar_url text,
  is_primary boolean not null default true,
  linked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index user_discord_accounts_discord_user_active_uidx
  on user_discord_accounts (discord_user_id)
  where deleted_at is null;
create unique index user_discord_accounts_primary_active_uidx
  on user_discord_accounts (user_id)
  where is_primary = true and deleted_at is null;

create table study_groups (
  id uuid primary key,
  owner_user_id uuid not null references users(id) on delete restrict,
  name varchar(120) not null,
  slug varchar(80) not null,
  description text,
  timezone varchar(64) not null default 'Asia/Seoul',
  visibility varchar(20) not null default 'invite_only',
  status varchar(20) not null default 'active',
  rules jsonb not null default '{}'::jsonb,
  schedule_defaults jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint study_groups_visibility_check check (visibility in ('private', 'invite_only', 'public')),
  constraint study_groups_status_check check (status in ('active', 'paused', 'archived'))
);

create unique index study_groups_slug_active_uidx
  on study_groups (slug)
  where deleted_at is null;
create index study_groups_owner_user_id_idx
  on study_groups (owner_user_id)
  where deleted_at is null;
create index study_groups_rules_gin_idx
  on study_groups using gin (rules);
create index study_groups_schedule_defaults_gin_idx
  on study_groups using gin (schedule_defaults);

create table study_group_members (
  id uuid primary key,
  group_id uuid not null references study_groups(id) on delete restrict,
  user_id uuid not null references users(id) on delete restrict,
  role varchar(20) not null default 'member',
  status varchar(20) not null default 'active',
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  preferences jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint study_group_members_role_check check (role in ('owner', 'manager', 'member')),
  constraint study_group_members_status_check check (status in ('active', 'paused', 'left', 'removed'))
);

create unique index study_group_members_group_user_active_uidx
  on study_group_members (group_id, user_id)
  where deleted_at is null;
create index study_group_members_user_id_idx
  on study_group_members (user_id)
  where deleted_at is null;

create table study_group_invitations (
  id uuid primary key,
  group_id uuid not null references study_groups(id) on delete restrict,
  inviter_member_id uuid not null references study_group_members(id) on delete restrict,
  accepted_by_user_id uuid references users(id) on delete restrict,
  invitee_email citext,
  invitee_discord_user_id varchar(40),
  token_hash varchar(128) not null,
  role varchar(20) not null default 'member',
  status varchar(20) not null default 'pending',
  expires_at timestamptz not null,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint study_group_invitations_role_check check (role in ('manager', 'member')),
  constraint study_group_invitations_status_check check (status in ('pending', 'accepted', 'expired', 'revoked'))
);

create unique index study_group_invitations_token_hash_active_uidx
  on study_group_invitations (token_hash)
  where deleted_at is null;
create index study_group_invitations_group_id_idx
  on study_group_invitations (group_id)
  where deleted_at is null;

create table study_sessions (
  id uuid primary key,
  group_id uuid not null references study_groups(id) on delete restrict,
  sequence_no int not null,
  title varchar(160) not null,
  status varchar(20) not null default 'scheduled',
  scheduled_start_at timestamptz not null,
  scheduled_end_at timestamptz not null,
  actual_start_at timestamptz,
  actual_end_at timestamptz,
  agenda jsonb not null default '{}'::jsonb,
  meeting_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint study_sessions_status_check check (status in ('scheduled', 'ready', 'in_progress', 'completed', 'cancelled')),
  constraint study_sessions_scheduled_window_check check (scheduled_end_at > scheduled_start_at),
  constraint study_sessions_actual_window_check check (actual_end_at is null or actual_start_at is null or actual_end_at >= actual_start_at)
);

create unique index study_sessions_group_sequence_active_uidx
  on study_sessions (group_id, sequence_no)
  where deleted_at is null;
create index study_sessions_group_scheduled_start_idx
  on study_sessions (group_id, scheduled_start_at desc)
  where deleted_at is null;

create table study_session_attendance (
  id uuid primary key,
  session_id uuid not null references study_sessions(id) on delete restrict,
  member_id uuid not null references study_group_members(id) on delete restrict,
  status varchar(20) not null default 'unknown',
  checked_in_at timestamptz,
  checked_out_at timestamptz,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint study_session_attendance_status_check check (status in ('unknown', 'attending', 'late', 'absent', 'excused'))
);

create unique index study_session_attendance_session_member_active_uidx
  on study_session_attendance (session_id, member_id)
  where deleted_at is null;
create index study_session_attendance_member_id_idx
  on study_session_attendance (member_id)
  where deleted_at is null;

create table study_session_notes (
  id uuid primary key,
  session_id uuid not null references study_sessions(id) on delete restrict,
  author_member_id uuid references study_group_members(id) on delete restrict,
  note_type varchar(30) not null,
  content text,
  structured_payload jsonb not null default '{}'::jsonb,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint study_session_notes_note_type_check check (note_type in ('pre_note', 'post_note', 'decision', 'blocker', 'summary'))
);

create index study_session_notes_session_type_idx
  on study_session_notes (session_id, note_type)
  where deleted_at is null;
create index study_session_notes_author_member_id_idx
  on study_session_notes (author_member_id)
  where author_member_id is not null and deleted_at is null;
create index study_session_notes_structured_payload_gin_idx
  on study_session_notes using gin (structured_payload);

create table study_session_action_items (
  id uuid primary key,
  session_id uuid not null references study_sessions(id) on delete restrict,
  source_note_id uuid references study_session_notes(id) on delete restrict,
  assigned_member_id uuid references study_group_members(id) on delete restrict,
  created_by_member_id uuid references study_group_members(id) on delete restrict,
  title varchar(200) not null,
  description text,
  status varchar(20) not null default 'open',
  due_date date,
  metadata jsonb not null default '{}'::jsonb,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint study_session_action_items_status_check check (status in ('open', 'in_progress', 'done', 'skipped', 'cancelled'))
);

create index study_session_action_items_assignee_status_due_idx
  on study_session_action_items (assigned_member_id, status, due_date)
  where deleted_at is null;
create index study_session_action_items_session_status_idx
  on study_session_action_items (session_id, status)
  where deleted_at is null;
create index study_session_action_items_source_note_id_idx
  on study_session_action_items (source_note_id)
  where source_note_id is not null and deleted_at is null;

create table study_goals (
  id uuid primary key,
  group_id uuid not null references study_groups(id) on delete restrict,
  owner_member_id uuid references study_group_members(id) on delete restrict,
  title varchar(160) not null,
  description text,
  status varchar(20) not null default 'active',
  target_date date,
  success_criteria jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint study_goals_status_check check (status in ('active', 'paused', 'completed', 'cancelled'))
);

create index study_goals_group_status_target_idx
  on study_goals (group_id, status, target_date)
  where deleted_at is null;
create index study_goals_owner_member_id_idx
  on study_goals (owner_member_id)
  where owner_member_id is not null and deleted_at is null;

create table member_progress_logs (
  id uuid primary key,
  member_id uuid not null references study_group_members(id) on delete restrict,
  goal_id uuid references study_goals(id) on delete restrict,
  session_id uuid references study_sessions(id) on delete restrict,
  summary text,
  progress_payload jsonb not null default '{}'::jsonb,
  logged_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index member_progress_logs_member_logged_idx
  on member_progress_logs (member_id, logged_at desc)
  where deleted_at is null;
create index member_progress_logs_goal_logged_idx
  on member_progress_logs (goal_id, logged_at desc)
  where goal_id is not null and deleted_at is null;
create index member_progress_logs_session_id_idx
  on member_progress_logs (session_id)
  where session_id is not null and deleted_at is null;
create index member_progress_logs_payload_gin_idx
  on member_progress_logs using gin (progress_payload);

create table study_resources (
  id uuid primary key,
  group_id uuid not null references study_groups(id) on delete restrict,
  added_by_member_id uuid references study_group_members(id) on delete restrict,
  resource_type varchar(30) not null,
  title varchar(180) not null,
  url text,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint study_resources_resource_type_check check (resource_type in ('link', 'document', 'book', 'video', 'repo', 'other'))
);

create index study_resources_group_type_idx
  on study_resources (group_id, resource_type)
  where deleted_at is null;
create index study_resources_added_by_member_id_idx
  on study_resources (added_by_member_id)
  where added_by_member_id is not null and deleted_at is null;

create table ai_prompt_runs (
  id uuid primary key,
  group_id uuid not null references study_groups(id) on delete restrict,
  session_id uuid references study_sessions(id) on delete restrict,
  requester_member_id uuid references study_group_members(id) on delete restrict,
  run_type varchar(40) not null,
  provider varchar(40) not null,
  model varchar(80) not null,
  prompt_version varchar(80) not null,
  status varchar(20) not null default 'queued',
  input_snapshot jsonb not null default '{}'::jsonb,
  output_payload jsonb not null default '{}'::jsonb,
  input_tokens int,
  output_tokens int,
  error_code varchar(80),
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint ai_prompt_runs_run_type_check check (run_type in ('preparation_brief', 'feedback_report', 'action_item_extraction', 'summary')),
  constraint ai_prompt_runs_status_check check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled'))
);

create index ai_prompt_runs_group_created_idx
  on ai_prompt_runs (group_id, created_at desc)
  where deleted_at is null;
create index ai_prompt_runs_session_type_created_idx
  on ai_prompt_runs (session_id, run_type, created_at desc)
  where session_id is not null and deleted_at is null;
create index ai_prompt_runs_requester_member_id_idx
  on ai_prompt_runs (requester_member_id)
  where requester_member_id is not null and deleted_at is null;

create table ai_preparation_briefs (
  id uuid primary key,
  session_id uuid not null references study_sessions(id) on delete restrict,
  prompt_run_id uuid not null references ai_prompt_runs(id) on delete restrict,
  version int not null,
  title varchar(180) not null,
  summary text not null,
  agenda_items jsonb not null default '[]'::jsonb,
  member_prompts jsonb not null default '[]'::jsonb,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index ai_preparation_briefs_session_version_active_uidx
  on ai_preparation_briefs (session_id, version)
  where deleted_at is null;
create unique index ai_preparation_briefs_prompt_run_active_uidx
  on ai_preparation_briefs (prompt_run_id)
  where deleted_at is null;
create index ai_preparation_briefs_agenda_items_gin_idx
  on ai_preparation_briefs using gin (agenda_items);
create index ai_preparation_briefs_member_prompts_gin_idx
  on ai_preparation_briefs using gin (member_prompts);

create table ai_feedback_reports (
  id uuid primary key,
  session_id uuid not null references study_sessions(id) on delete restrict,
  target_member_id uuid references study_group_members(id) on delete restrict,
  prompt_run_id uuid not null references ai_prompt_runs(id) on delete restrict,
  version int not null,
  report_type varchar(30) not null,
  summary text not null,
  strengths jsonb not null default '[]'::jsonb,
  improvements jsonb not null default '[]'::jsonb,
  next_actions jsonb not null default '[]'::jsonb,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint ai_feedback_reports_report_type_check check (report_type in ('group', 'individual')),
  constraint ai_feedback_reports_target_check check (
    (report_type = 'group' and target_member_id is null)
    or
    (report_type = 'individual' and target_member_id is not null)
  )
);

create unique index ai_feedback_reports_target_version_active_uidx
  on ai_feedback_reports (
    session_id,
    report_type,
    coalesce(target_member_id, '00000000-0000-0000-0000-000000000000'::uuid),
    version
  )
  where deleted_at is null;
create unique index ai_feedback_reports_prompt_run_active_uidx
  on ai_feedback_reports (prompt_run_id)
  where deleted_at is null;

create table discord_notification_channels (
  id uuid primary key,
  group_id uuid not null references study_groups(id) on delete restrict,
  discord_guild_id varchar(40) not null,
  discord_channel_id varchar(40) not null,
  channel_name varchar(120),
  status varchar(20) not null default 'active',
  notification_settings jsonb not null default '{}'::jsonb,
  connected_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint discord_notification_channels_status_check check (status in ('active', 'disabled', 'revoked'))
);

create unique index discord_notification_channels_group_channel_active_uidx
  on discord_notification_channels (group_id, discord_channel_id)
  where deleted_at is null;
create index discord_notification_channels_settings_gin_idx
  on discord_notification_channels using gin (notification_settings);

create table discord_notification_logs (
  id uuid primary key,
  channel_id uuid not null references discord_notification_channels(id) on delete restrict,
  session_id uuid references study_sessions(id) on delete restrict,
  recipient_user_id uuid references users(id) on delete restrict,
  notification_type varchar(40) not null,
  status varchar(20) not null default 'pending',
  provider_message_id varchar(80),
  payload jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz,
  sent_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint discord_notification_logs_type_check check (notification_type in ('session_reminder', 'prep_brief', 'feedback_ready', 'action_item_due')),
  constraint discord_notification_logs_status_check check (status in ('pending', 'sent', 'failed', 'skipped'))
);

create index discord_notification_logs_status_scheduled_idx
  on discord_notification_logs (status, scheduled_for)
  where deleted_at is null;
create index discord_notification_logs_session_type_idx
  on discord_notification_logs (session_id, notification_type)
  where session_id is not null and deleted_at is null;
create index discord_notification_logs_channel_id_idx
  on discord_notification_logs (channel_id)
  where deleted_at is null;
create index discord_notification_logs_recipient_user_id_idx
  on discord_notification_logs (recipient_user_id)
  where recipient_user_id is not null and deleted_at is null;
