package com.studypot.aistudyleader.llm.domain;

public enum LlmUsagePurpose {
	DETAIL_KEYWORD_SUGGEST,
	CURRICULUM_GENERATE,
	CURRICULUM_REGENERATE_WEEK,
	TEAM_LEAD_CHAT,
	RETROSPECTIVE_ANALYZE,
	RETROSPECTIVE_FEEDBACK,
	NEXT_WEEK_ADJUST
}
